title: Francesco Paolo Lezza
# email: 
description: >- # this means “folded” text
  A simple Jekyll site example.
baseurl: ""                           # leave empty for user site, or put project repo name here
url: "https://github.com/FrancescoPaoloL" # replace with your GitHub URL

# theme: minima
plugins: []

