title: Francesco Paolo Lezza
# email:
description: >- # this means “folded” text
  My simple Jekyll personal site.
baseurl: ""                           # leave empty for user site, or put project repo name here
url: "https://github.com/FrancescoPaoloL" # replace with your GitHub URL

# theme: minima
plugins: []

timezone: Europe/Rome

